theme = "terminal"
baseURL = "https://hacklabreus.org"
languageCode = "es"
title = "HacklabReus"

[params]
  favicon = "images/hacklabreus.ico"
  [params.Logo]
  logoText = "HacklabReus"
  logoImage = "img/glide.png"
  LogoHomeLink = "/"

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Inicio"
    url = "/"
    weight = 1

[[menu.main]]
    identifier = "blog"
    name = "Blog"
    url = "/posts/"
    weight = 2

[[menu.main]]
    identifier = "agenda"
    name = "Agenda"
    url = "/agenda/"
    weight = 3

  [[menu.main]]
    identifier = "about"
    name = "Acerca de"
    url = "/about/"
    weight = 4

  [[menu.main]]
    identifier = "contact"
    name = "Contacto"
    url = "/contact/"
    weight = 5
