theme = "terminal"
baseURL = "https://hacklabreus.org"
languageCode = "es"
title = "HacklabReus"
description = "Blog y web de conferencias de seguridad informática Hacklabreus Hack lab Reus"
keywords = ["hacklabreus","Reus","ciberseguridad","hacking ético", "seguridad informática", "conferencias"]
pagination.pagerSize = 5

buildDrafts: false
buildFuture: false
buildExpired: false
disableHugoGeneratorInject = true
disableKinds = ["RSS", "sitemap", "robotsTXT"]

[minify]
  disableXML = true       # No minificar XML (feeds, sitemap)
  minifyOutput = true     # Minificar HTML, CSS, JS


# Required for Chroma and the custom syntax highlighting.
[markup.highlight]
  noClasses = false

[params]
  customCSS = ["css/custom.css"]
  # show selector to switch language
  showLanguageSelector = false

  # set theme to full screen width
  fullWidthTheme = false

  # center theme with default width
  centerTheme = true

  # set post to show the last updated
  # If you use git, you can set `enableGitInfo` to `true` and then post will automatically get the last updated
  showLastUpdated = false

  # Provide a string as a prefix for the last update date. By default, it looks like this: 2020-xx-xx [Updated: 2020-xx-xx] :: Author
  # updatedDatePrefix = "Updated"

  # whether to show a page's estimated reading time
  # readingTime = false # default

  # dateFormat = "2006-01-02"

  [params.Logo]
  logoText = "HacklabReus"
  logoImage = "img/logo.png"
  LogoHomeLink = "/"

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Inici"
    url = "/"
    weight = 1

[[menu.main]]
    identifier = "blog"
    name = "Blog"
    url = "/posts/"
    weight = 2

[[menu.main]]
    identifier = "agenda"
    name = "Agenda"
    url = "/agenda/"
    weight = 3

  [[menu.main]]
    identifier = "about"
    name = "Qui som"
    url = "/about/"
    weight = 4

  [[menu.main]]
    identifier = "contact"
    name = "Contacte"
    url = "/contact/"
    weight = 5
