backend:
  name: github
  repo: ganxetdev/nodedev
  branch: main
  auth_type: implicit
  app_id: Ov23liShPNZE7mlcssqX

media_folder: static/images
public_folder: /images

collections:
  - name: "posts"
    label: "Posts"
    folder: "content/posts"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Títol", name: "title", widget: "string"}
      - {label: "Data", name: "date", widget: "datetime", format: "YYYY-MM-DD", time_format: false}
      - {label: "Contingut", name: "body", widget: "markdown"}